### ISSUE TITLE
'TESTID' not defined

### ISSUE THREAD

**Issue by dmitris** [prbinu/xss-checkmate#2]
When trying to run the script, I'm getting the error below - is TESTID supposed to be defined?

```
ERROR: test_run (__main__.XSSTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "xsscheckmate-gruyere-demo.py", line 54, in test_run
    self.result()
  File "xsscheckmate-gruyere-demo.py", line 59, in result
    if -1 != str(cmsg).find(" " + TESTID):
NameError: global name 'TESTID' is not defined
```

**Comment by prbinu** [comment]
Dimitry, thanks for reporting this issue. please try now.
